services:
  unmonitarr:
    image: ghcr.io/nicolas-gatta/unmonitarr:latest
    container_name: unmonitarr
    restart: unless-stopped
    ports:
      - "5056:5055"
    volumes:
      - /opt/unmonitarr/data:/app/data
    environment:
      - TZ=Europe/Brussels
      - LOG_LEVEL=INFO